name: Archive Trilium Shared Note

on:
  schedule:
    - cron: '0 9 * * *'   # Runs at 12 PM Bucharest (UTC+3 → 9:00 UTC)
  workflow_dispatch:        # Manual trigger from GitHub UI

jobs:
  fetch-note:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Download Trilium shared note
        run: |
          curl -sSL "http://2ndbrain.psychlab.eu:22002/share/z09ChFJuqwaG" -o Go_to_study.html
          curl -sSL "http://2ndbrain.psychlab.eu:22002/share/fv1ENOuExVYS" -o Go_to_get.html

      - name: Generate index.html
        run: |
          echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Trilium Notes</title></head><body><h1>Archived Notes</h1><ul>" > index.html
          for file in note*.html; do
            echo "<li><a href=\"$file\">$file</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add *.html
          git commit -m "Update all notes [auto]" || echo "Nothing to commit"
          git push origin HEAD:main
