name: Archive Trilium Shared Note

on:
  schedule:
    - cron: '0 21 * * *'   # Runs at 12 AM Bucharest (UTC+3 → 21:00 UTC)
  workflow_dispatch:        # Manual trigger from GitHub UI

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0           # required for pushing to branch

      - name: Set up branch name
        run: |
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Download Trilium shared note
        run: |
          curl -sSL "http://2ndbrain.psychlab.eu:22002/share/z09ChFJuqwaG" -o index.html

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add index.html
          git commit -m "Update shared note [auto]" || echo "Nothing to commit"
          git push origin HEAD:$BRANCH_NAME
